---

- name: Install requirements
  apt: name=python-apt state=installed

- name: Add package repository
  apt_repository: repo='deb http://http.debian.net/debian jessie-backports main'

- name: Install package
  apt: name=docker.io state=present update_cache=yes

- name: Create system group
  group: name=docker system=yes state=present

- name: Create system user
  user: name=docker system=yes state=present

- name: Configure service
  template: src=defaults.j2 dest=/etc/default/docker
  notify: restart docker

- name: Enable service
  service: name=docker state=started enabled=yes
