---
# tasks file for snmp

- name: Install package
  apt: name=snmpd state=present

- name: Create config directory
  action: file path=/etc/snmp state=directory owner=0 group=0 mode=0755

- name: Configure service
  template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf
  notify: restart snmpd

- name: Configure service defaults
  template: src=snmpd-defaults.j2 dest=/etc/default/snmpd
  notify: restart snmpd

- name: Enable service
  service: name=snmpd enabled=yes
